stages:
  - test
  - build1

#format:
#  image: golang:latest
#  stage: test
#  script:
#    - go fmt $(go list ./... | grep -v /vendor/)
#    - go vet $(go list ./... | grep -v /vendor/)
#    - go test -race $(go list ./... | grep -v /vendor/)

build-go:
  tags:
    - linux
    - docker
  image: golang:latest
  stage: build1
  script:
    - cd cmd/nginxmetrics
    - go build -x 
  artifacts:
    paths:
      - cmd/nginxmetrics/nginxmetrics
      - cmd/nginxmetrics/nginx.config.json
